<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/tx-push/proxy.proto

namespace Sa\Rpc\Cli\Proxy;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sa.rpc.cli.proxy.SubscriptionRsp</code>
 */
class SubscriptionRsp extends \Google\Protobuf\Internal\Message
{
    /**
     *响应头
     *
     * Generated from protobuf field <code>.sa.rpc.cli.proxy.Rsp rsp = 1;</code>
     */
    protected $rsp = null;
    /**
     *消息数据
     *
     * Generated from protobuf field <code>.sa.rpc.entity.Subscription data = 4;</code>
     */
    protected $data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Sa\Rpc\Cli\Proxy\Rsp $rsp
     *          响应头
     *     @type \Sa\Rpc\Entity\Subscription $data
     *          消息数据
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\TxPush\Proxy::initOnce();
        parent::__construct($data);
    }

    /**
     *响应头
     *
     * Generated from protobuf field <code>.sa.rpc.cli.proxy.Rsp rsp = 1;</code>
     * @return \Sa\Rpc\Cli\Proxy\Rsp|null
     */
    public function getRsp()
    {
        return $this->rsp;
    }

    public function hasRsp()
    {
        return isset($this->rsp);
    }

    public function clearRsp()
    {
        unset($this->rsp);
    }

    /**
     *响应头
     *
     * Generated from protobuf field <code>.sa.rpc.cli.proxy.Rsp rsp = 1;</code>
     * @param \Sa\Rpc\Cli\Proxy\Rsp $var
     * @return $this
     */
    public function setRsp($var)
    {
        GPBUtil::checkMessage($var, \Sa\Rpc\Cli\Proxy\Rsp::class);
        $this->rsp = $var;

        return $this;
    }

    /**
     *消息数据
     *
     * Generated from protobuf field <code>.sa.rpc.entity.Subscription data = 4;</code>
     * @return \Sa\Rpc\Entity\Subscription|null
     */
    public function getData()
    {
        return $this->data;
    }

    public function hasData()
    {
        return isset($this->data);
    }

    public function clearData()
    {
        unset($this->data);
    }

    /**
     *消息数据
     *
     * Generated from protobuf field <code>.sa.rpc.entity.Subscription data = 4;</code>
     * @param \Sa\Rpc\Entity\Subscription $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Sa\Rpc\Entity\Subscription::class);
        $this->data = $var;

        return $this;
    }

}

