<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/tx-push/entity.proto

namespace Sa\Rpc\Entity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *股票十档行情
 *
 * Generated from protobuf message <code>sa.rpc.entity.StockQuoteRecord</code>
 */
class StockQuoteRecord extends \Google\Protobuf\Internal\Message
{
    /**
     *证券市场，见数据字典
     *
     * Generated from protobuf field <code>uint32 stock_exchange = 1;</code>
     */
    protected $stock_exchange = 0;
    /**
     *证券代码
     *
     * Generated from protobuf field <code>string stock_code = 2;</code>
     */
    protected $stock_code = '';
    /**
     *快照日期时间戳(毫秒)
     *
     * Generated from protobuf field <code>int64 created_at = 3;</code>
     */
    protected $created_at = 0;
    /**
     *状态：0-开盘前，1-开盘集合竞价，2-集合竞价至连续竞价，3-连续竞价，4-中午休市，5-收盘集合竞价，6-闭市
     *
     * Generated from protobuf field <code>uint32 status = 4;</code>
     */
    protected $status = 0;
    /**
     *前收盘价
     *
     * Generated from protobuf field <code>uint32 prev_close_price = 5;</code>
     */
    protected $prev_close_price = 0;
    /**
     *开盘价
     *
     * Generated from protobuf field <code>uint32 open_price = 6;</code>
     */
    protected $open_price = 0;
    /**
     *最新价
     *
     * Generated from protobuf field <code>uint32 latest_price = 7;</code>
     */
    protected $latest_price = 0;
    /**
     *最高价
     *
     * Generated from protobuf field <code>uint32 high_price = 8;</code>
     */
    protected $high_price = 0;
    /**
     *最低价
     *
     * Generated from protobuf field <code>uint32 low_price = 9;</code>
     */
    protected $low_price = 0;
    /**
     *涨停价
     *
     * Generated from protobuf field <code>uint32 limit_up_price = 10;</code>
     */
    protected $limit_up_price = 0;
    /**
     *跌停价
     *
     * Generated from protobuf field <code>uint32 limit_down_price = 11;</code>
     */
    protected $limit_down_price = 0;
    /**
     *成交笔数
     *
     * Generated from protobuf field <code>uint32 order_quantity = 12;</code>
     */
    protected $order_quantity = 0;
    /**
     *成交数量
     *
     * Generated from protobuf field <code>uint64 volume = 13;</code>
     */
    protected $volume = 0;
    /**
     *成交金额
     *
     * Generated from protobuf field <code>uint64 amount = 14;</code>
     */
    protected $amount = 0;
    /**
     *委托买入数量
     *
     * Generated from protobuf field <code>uint64 bid_volume = 15;</code>
     */
    protected $bid_volume = 0;
    /**
     *委托买入加权平均价
     *
     * Generated from protobuf field <code>uint32 bid_price = 16;</code>
     */
    protected $bid_price = 0;
    /**
     *委托卖出数量
     *
     * Generated from protobuf field <code>uint64 ask_volume = 17;</code>
     */
    protected $ask_volume = 0;
    /**
     *委托卖出加权平均价
     *
     * Generated from protobuf field <code>uint32 ask_price = 18;</code>
     */
    protected $ask_price = 0;
    /**
     *委托买入价格明细(十档)
     *
     * Generated from protobuf field <code>repeated uint32 bid_price_detail = 19;</code>
     */
    private $bid_price_detail;
    /**
     *委托买入数量明细(十档)
     *
     * Generated from protobuf field <code>repeated uint32 bid_volume_detail = 20;</code>
     */
    private $bid_volume_detail;
    /**
     *委托卖出价格明细(十档)
     *
     * Generated from protobuf field <code>repeated uint32 ask_price_detail = 21;</code>
     */
    private $ask_price_detail;
    /**
     *委托卖出数量明细(十档)
     *
     * Generated from protobuf field <code>repeated uint32 ask_volume_detail = 22;</code>
     */
    private $ask_volume_detail;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $stock_exchange
     *          证券市场，见数据字典
     *     @type string $stock_code
     *          证券代码
     *     @type int|string $created_at
     *          快照日期时间戳(毫秒)
     *     @type int $status
     *          状态：0-开盘前，1-开盘集合竞价，2-集合竞价至连续竞价，3-连续竞价，4-中午休市，5-收盘集合竞价，6-闭市
     *     @type int $prev_close_price
     *          前收盘价
     *     @type int $open_price
     *          开盘价
     *     @type int $latest_price
     *          最新价
     *     @type int $high_price
     *          最高价
     *     @type int $low_price
     *          最低价
     *     @type int $limit_up_price
     *          涨停价
     *     @type int $limit_down_price
     *          跌停价
     *     @type int $order_quantity
     *          成交笔数
     *     @type int|string $volume
     *          成交数量
     *     @type int|string $amount
     *          成交金额
     *     @type int|string $bid_volume
     *          委托买入数量
     *     @type int $bid_price
     *          委托买入加权平均价
     *     @type int|string $ask_volume
     *          委托卖出数量
     *     @type int $ask_price
     *          委托卖出加权平均价
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $bid_price_detail
     *          委托买入价格明细(十档)
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $bid_volume_detail
     *          委托买入数量明细(十档)
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $ask_price_detail
     *          委托卖出价格明细(十档)
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $ask_volume_detail
     *          委托卖出数量明细(十档)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\TxPush\Entity::initOnce();
        parent::__construct($data);
    }

    /**
     *证券市场，见数据字典
     *
     * Generated from protobuf field <code>uint32 stock_exchange = 1;</code>
     * @return int
     */
    public function getStockExchange()
    {
        return $this->stock_exchange;
    }

    /**
     *证券市场，见数据字典
     *
     * Generated from protobuf field <code>uint32 stock_exchange = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStockExchange($var)
    {
        GPBUtil::checkUint32($var);
        $this->stock_exchange = $var;

        return $this;
    }

    /**
     *证券代码
     *
     * Generated from protobuf field <code>string stock_code = 2;</code>
     * @return string
     */
    public function getStockCode()
    {
        return $this->stock_code;
    }

    /**
     *证券代码
     *
     * Generated from protobuf field <code>string stock_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStockCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->stock_code = $var;

        return $this;
    }

    /**
     *快照日期时间戳(毫秒)
     *
     * Generated from protobuf field <code>int64 created_at = 3;</code>
     * @return int|string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     *快照日期时间戳(毫秒)
     *
     * Generated from protobuf field <code>int64 created_at = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     *状态：0-开盘前，1-开盘集合竞价，2-集合竞价至连续竞价，3-连续竞价，4-中午休市，5-收盘集合竞价，6-闭市
     *
     * Generated from protobuf field <code>uint32 status = 4;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     *状态：0-开盘前，1-开盘集合竞价，2-集合竞价至连续竞价，3-连续竞价，4-中午休市，5-收盘集合竞价，6-闭市
     *
     * Generated from protobuf field <code>uint32 status = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->status = $var;

        return $this;
    }

    /**
     *前收盘价
     *
     * Generated from protobuf field <code>uint32 prev_close_price = 5;</code>
     * @return int
     */
    public function getPrevClosePrice()
    {
        return $this->prev_close_price;
    }

    /**
     *前收盘价
     *
     * Generated from protobuf field <code>uint32 prev_close_price = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPrevClosePrice($var)
    {
        GPBUtil::checkUint32($var);
        $this->prev_close_price = $var;

        return $this;
    }

    /**
     *开盘价
     *
     * Generated from protobuf field <code>uint32 open_price = 6;</code>
     * @return int
     */
    public function getOpenPrice()
    {
        return $this->open_price;
    }

    /**
     *开盘价
     *
     * Generated from protobuf field <code>uint32 open_price = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setOpenPrice($var)
    {
        GPBUtil::checkUint32($var);
        $this->open_price = $var;

        return $this;
    }

    /**
     *最新价
     *
     * Generated from protobuf field <code>uint32 latest_price = 7;</code>
     * @return int
     */
    public function getLatestPrice()
    {
        return $this->latest_price;
    }

    /**
     *最新价
     *
     * Generated from protobuf field <code>uint32 latest_price = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setLatestPrice($var)
    {
        GPBUtil::checkUint32($var);
        $this->latest_price = $var;

        return $this;
    }

    /**
     *最高价
     *
     * Generated from protobuf field <code>uint32 high_price = 8;</code>
     * @return int
     */
    public function getHighPrice()
    {
        return $this->high_price;
    }

    /**
     *最高价
     *
     * Generated from protobuf field <code>uint32 high_price = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setHighPrice($var)
    {
        GPBUtil::checkUint32($var);
        $this->high_price = $var;

        return $this;
    }

    /**
     *最低价
     *
     * Generated from protobuf field <code>uint32 low_price = 9;</code>
     * @return int
     */
    public function getLowPrice()
    {
        return $this->low_price;
    }

    /**
     *最低价
     *
     * Generated from protobuf field <code>uint32 low_price = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setLowPrice($var)
    {
        GPBUtil::checkUint32($var);
        $this->low_price = $var;

        return $this;
    }

    /**
     *涨停价
     *
     * Generated from protobuf field <code>uint32 limit_up_price = 10;</code>
     * @return int
     */
    public function getLimitUpPrice()
    {
        return $this->limit_up_price;
    }

    /**
     *涨停价
     *
     * Generated from protobuf field <code>uint32 limit_up_price = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setLimitUpPrice($var)
    {
        GPBUtil::checkUint32($var);
        $this->limit_up_price = $var;

        return $this;
    }

    /**
     *跌停价
     *
     * Generated from protobuf field <code>uint32 limit_down_price = 11;</code>
     * @return int
     */
    public function getLimitDownPrice()
    {
        return $this->limit_down_price;
    }

    /**
     *跌停价
     *
     * Generated from protobuf field <code>uint32 limit_down_price = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setLimitDownPrice($var)
    {
        GPBUtil::checkUint32($var);
        $this->limit_down_price = $var;

        return $this;
    }

    /**
     *成交笔数
     *
     * Generated from protobuf field <code>uint32 order_quantity = 12;</code>
     * @return int
     */
    public function getOrderQuantity()
    {
        return $this->order_quantity;
    }

    /**
     *成交笔数
     *
     * Generated from protobuf field <code>uint32 order_quantity = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderQuantity($var)
    {
        GPBUtil::checkUint32($var);
        $this->order_quantity = $var;

        return $this;
    }

    /**
     *成交数量
     *
     * Generated from protobuf field <code>uint64 volume = 13;</code>
     * @return int|string
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     *成交数量
     *
     * Generated from protobuf field <code>uint64 volume = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkUint64($var);
        $this->volume = $var;

        return $this;
    }

    /**
     *成交金额
     *
     * Generated from protobuf field <code>uint64 amount = 14;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     *成交金额
     *
     * Generated from protobuf field <code>uint64 amount = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkUint64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     *委托买入数量
     *
     * Generated from protobuf field <code>uint64 bid_volume = 15;</code>
     * @return int|string
     */
    public function getBidVolume()
    {
        return $this->bid_volume;
    }

    /**
     *委托买入数量
     *
     * Generated from protobuf field <code>uint64 bid_volume = 15;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBidVolume($var)
    {
        GPBUtil::checkUint64($var);
        $this->bid_volume = $var;

        return $this;
    }

    /**
     *委托买入加权平均价
     *
     * Generated from protobuf field <code>uint32 bid_price = 16;</code>
     * @return int
     */
    public function getBidPrice()
    {
        return $this->bid_price;
    }

    /**
     *委托买入加权平均价
     *
     * Generated from protobuf field <code>uint32 bid_price = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setBidPrice($var)
    {
        GPBUtil::checkUint32($var);
        $this->bid_price = $var;

        return $this;
    }

    /**
     *委托卖出数量
     *
     * Generated from protobuf field <code>uint64 ask_volume = 17;</code>
     * @return int|string
     */
    public function getAskVolume()
    {
        return $this->ask_volume;
    }

    /**
     *委托卖出数量
     *
     * Generated from protobuf field <code>uint64 ask_volume = 17;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAskVolume($var)
    {
        GPBUtil::checkUint64($var);
        $this->ask_volume = $var;

        return $this;
    }

    /**
     *委托卖出加权平均价
     *
     * Generated from protobuf field <code>uint32 ask_price = 18;</code>
     * @return int
     */
    public function getAskPrice()
    {
        return $this->ask_price;
    }

    /**
     *委托卖出加权平均价
     *
     * Generated from protobuf field <code>uint32 ask_price = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setAskPrice($var)
    {
        GPBUtil::checkUint32($var);
        $this->ask_price = $var;

        return $this;
    }

    /**
     *委托买入价格明细(十档)
     *
     * Generated from protobuf field <code>repeated uint32 bid_price_detail = 19;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBidPriceDetail()
    {
        return $this->bid_price_detail;
    }

    /**
     *委托买入价格明细(十档)
     *
     * Generated from protobuf field <code>repeated uint32 bid_price_detail = 19;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBidPriceDetail($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->bid_price_detail = $arr;

        return $this;
    }

    /**
     *委托买入数量明细(十档)
     *
     * Generated from protobuf field <code>repeated uint32 bid_volume_detail = 20;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBidVolumeDetail()
    {
        return $this->bid_volume_detail;
    }

    /**
     *委托买入数量明细(十档)
     *
     * Generated from protobuf field <code>repeated uint32 bid_volume_detail = 20;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBidVolumeDetail($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->bid_volume_detail = $arr;

        return $this;
    }

    /**
     *委托卖出价格明细(十档)
     *
     * Generated from protobuf field <code>repeated uint32 ask_price_detail = 21;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAskPriceDetail()
    {
        return $this->ask_price_detail;
    }

    /**
     *委托卖出价格明细(十档)
     *
     * Generated from protobuf field <code>repeated uint32 ask_price_detail = 21;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAskPriceDetail($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->ask_price_detail = $arr;

        return $this;
    }

    /**
     *委托卖出数量明细(十档)
     *
     * Generated from protobuf field <code>repeated uint32 ask_volume_detail = 22;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAskVolumeDetail()
    {
        return $this->ask_volume_detail;
    }

    /**
     *委托卖出数量明细(十档)
     *
     * Generated from protobuf field <code>repeated uint32 ask_volume_detail = 22;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAskVolumeDetail($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->ask_volume_detail = $arr;

        return $this;
    }

}

