<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/tx-push/entity.proto

namespace Sa\Rpc\Entity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *订阅信息
 *
 * Generated from protobuf message <code>sa.rpc.entity.Subscription</code>
 */
class Subscription extends \Google\Protobuf\Internal\Message
{
    /**
     *订阅主题，多个逗号分隔
     *
     * Generated from protobuf field <code>string topic = 1;</code>
     */
    protected $topic = '';
    /**
     *订阅主题正则表达式，如果设置此属性，则topic设置无效
     *
     * Generated from protobuf field <code>string topic_pattern = 2;</code>
     */
    protected $topic_pattern = '';
    /**
     *是否订阅全部
     *
     * Generated from protobuf field <code>bool is_sub_all = 3;</code>
     */
    protected $is_sub_all = false;
    /**
     *订阅失效日期
     *
     * Generated from protobuf field <code>int64 expired_at = 4;</code>
     */
    protected $expired_at = 0;
    /**
     *最大订阅数
     *
     * Generated from protobuf field <code>uint32 max_subscribe_count = 5;</code>
     */
    protected $max_subscribe_count = 0;
    /**
     *已有订阅数
     *
     * Generated from protobuf field <code>uint32 used_subscribe_count = 6;</code>
     */
    protected $used_subscribe_count = 0;
    /**
     *更新版本号
     *
     * Generated from protobuf field <code>int64 version = 7;</code>
     */
    protected $version = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $topic
     *          订阅主题，多个逗号分隔
     *     @type string $topic_pattern
     *          订阅主题正则表达式，如果设置此属性，则topic设置无效
     *     @type bool $is_sub_all
     *          是否订阅全部
     *     @type int|string $expired_at
     *          订阅失效日期
     *     @type int $max_subscribe_count
     *          最大订阅数
     *     @type int $used_subscribe_count
     *          已有订阅数
     *     @type int|string $version
     *          更新版本号
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\TxPush\Entity::initOnce();
        parent::__construct($data);
    }

    /**
     *订阅主题，多个逗号分隔
     *
     * Generated from protobuf field <code>string topic = 1;</code>
     * @return string
     */
    public function getTopic()
    {
        return $this->topic;
    }

    /**
     *订阅主题，多个逗号分隔
     *
     * Generated from protobuf field <code>string topic = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTopic($var)
    {
        GPBUtil::checkString($var, True);
        $this->topic = $var;

        return $this;
    }

    /**
     *订阅主题正则表达式，如果设置此属性，则topic设置无效
     *
     * Generated from protobuf field <code>string topic_pattern = 2;</code>
     * @return string
     */
    public function getTopicPattern()
    {
        return $this->topic_pattern;
    }

    /**
     *订阅主题正则表达式，如果设置此属性，则topic设置无效
     *
     * Generated from protobuf field <code>string topic_pattern = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTopicPattern($var)
    {
        GPBUtil::checkString($var, True);
        $this->topic_pattern = $var;

        return $this;
    }

    /**
     *是否订阅全部
     *
     * Generated from protobuf field <code>bool is_sub_all = 3;</code>
     * @return bool
     */
    public function getIsSubAll()
    {
        return $this->is_sub_all;
    }

    /**
     *是否订阅全部
     *
     * Generated from protobuf field <code>bool is_sub_all = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSubAll($var)
    {
        GPBUtil::checkBool($var);
        $this->is_sub_all = $var;

        return $this;
    }

    /**
     *订阅失效日期
     *
     * Generated from protobuf field <code>int64 expired_at = 4;</code>
     * @return int|string
     */
    public function getExpiredAt()
    {
        return $this->expired_at;
    }

    /**
     *订阅失效日期
     *
     * Generated from protobuf field <code>int64 expired_at = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpiredAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->expired_at = $var;

        return $this;
    }

    /**
     *最大订阅数
     *
     * Generated from protobuf field <code>uint32 max_subscribe_count = 5;</code>
     * @return int
     */
    public function getMaxSubscribeCount()
    {
        return $this->max_subscribe_count;
    }

    /**
     *最大订阅数
     *
     * Generated from protobuf field <code>uint32 max_subscribe_count = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxSubscribeCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->max_subscribe_count = $var;

        return $this;
    }

    /**
     *已有订阅数
     *
     * Generated from protobuf field <code>uint32 used_subscribe_count = 6;</code>
     * @return int
     */
    public function getUsedSubscribeCount()
    {
        return $this->used_subscribe_count;
    }

    /**
     *已有订阅数
     *
     * Generated from protobuf field <code>uint32 used_subscribe_count = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setUsedSubscribeCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->used_subscribe_count = $var;

        return $this;
    }

    /**
     *更新版本号
     *
     * Generated from protobuf field <code>int64 version = 7;</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     *更新版本号
     *
     * Generated from protobuf field <code>int64 version = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->version = $var;

        return $this;
    }

}

