<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/tx-push/entity.proto

namespace Sa\Rpc\Entity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *逐笔成交
 *
 * Generated from protobuf message <code>sa.rpc.entity.TickRecord</code>
 */
class TickRecord extends \Google\Protobuf\Internal\Message
{
    /**
     *证券市场，1-SH，2-SZ
     *
     * Generated from protobuf field <code>uint32 stock_exchange = 1;</code>
     */
    protected $stock_exchange = 0;
    /**
     *证券代码
     *
     * Generated from protobuf field <code>string stock_code = 2;</code>
     */
    protected $stock_code = '';
    /**
     *成交日期时间戳(毫秒)
     *
     * Generated from protobuf field <code>int64 created_at = 3;</code>
     */
    protected $created_at = 0;
    /**
     *成交编号
     *
     * Generated from protobuf field <code>string code = 4;</code>
     */
    protected $code = '';
    /**
     *成交单价
     *
     * Generated from protobuf field <code>uint32 price = 5;</code>
     */
    protected $price = 0;
    /**
     *成交数量
     *
     * Generated from protobuf field <code>uint64 volume = 6;</code>
     */
    protected $volume = 0;
    /**
     *成交金额
     *
     * Generated from protobuf field <code>uint64 amount = 7;</code>
     */
    protected $amount = 0;
    /**
     *交易方向：0-未知，1-买方成交，2-卖方成交
     *
     * Generated from protobuf field <code>uint32 tx_dir = 8;</code>
     */
    protected $tx_dir = 0;
    /**
     *交易类型：0-成交，1-撤单
     *
     * Generated from protobuf field <code>uint32 tx_kind = 9;</code>
     */
    protected $tx_kind = 0;
    /**
     *买方委托序号
     *
     * Generated from protobuf field <code>string buy_order_seq = 10;</code>
     */
    protected $buy_order_seq = '';
    /**
     *卖方委托序号
     *
     * Generated from protobuf field <code>string sell_order_seq = 11;</code>
     */
    protected $sell_order_seq = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $stock_exchange
     *          证券市场，1-SH，2-SZ
     *     @type string $stock_code
     *          证券代码
     *     @type int|string $created_at
     *          成交日期时间戳(毫秒)
     *     @type string $code
     *          成交编号
     *     @type int $price
     *          成交单价
     *     @type int|string $volume
     *          成交数量
     *     @type int|string $amount
     *          成交金额
     *     @type int $tx_dir
     *          交易方向：0-未知，1-买方成交，2-卖方成交
     *     @type int $tx_kind
     *          交易类型：0-成交，1-撤单
     *     @type string $buy_order_seq
     *          买方委托序号
     *     @type string $sell_order_seq
     *          卖方委托序号
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\TxPush\Entity::initOnce();
        parent::__construct($data);
    }

    /**
     *证券市场，1-SH，2-SZ
     *
     * Generated from protobuf field <code>uint32 stock_exchange = 1;</code>
     * @return int
     */
    public function getStockExchange()
    {
        return $this->stock_exchange;
    }

    /**
     *证券市场，1-SH，2-SZ
     *
     * Generated from protobuf field <code>uint32 stock_exchange = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStockExchange($var)
    {
        GPBUtil::checkUint32($var);
        $this->stock_exchange = $var;

        return $this;
    }

    /**
     *证券代码
     *
     * Generated from protobuf field <code>string stock_code = 2;</code>
     * @return string
     */
    public function getStockCode()
    {
        return $this->stock_code;
    }

    /**
     *证券代码
     *
     * Generated from protobuf field <code>string stock_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStockCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->stock_code = $var;

        return $this;
    }

    /**
     *成交日期时间戳(毫秒)
     *
     * Generated from protobuf field <code>int64 created_at = 3;</code>
     * @return int|string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     *成交日期时间戳(毫秒)
     *
     * Generated from protobuf field <code>int64 created_at = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     *成交编号
     *
     * Generated from protobuf field <code>string code = 4;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     *成交编号
     *
     * Generated from protobuf field <code>string code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     *成交单价
     *
     * Generated from protobuf field <code>uint32 price = 5;</code>
     * @return int
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     *成交单价
     *
     * Generated from protobuf field <code>uint32 price = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkUint32($var);
        $this->price = $var;

        return $this;
    }

    /**
     *成交数量
     *
     * Generated from protobuf field <code>uint64 volume = 6;</code>
     * @return int|string
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     *成交数量
     *
     * Generated from protobuf field <code>uint64 volume = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkUint64($var);
        $this->volume = $var;

        return $this;
    }

    /**
     *成交金额
     *
     * Generated from protobuf field <code>uint64 amount = 7;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     *成交金额
     *
     * Generated from protobuf field <code>uint64 amount = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkUint64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     *交易方向：0-未知，1-买方成交，2-卖方成交
     *
     * Generated from protobuf field <code>uint32 tx_dir = 8;</code>
     * @return int
     */
    public function getTxDir()
    {
        return $this->tx_dir;
    }

    /**
     *交易方向：0-未知，1-买方成交，2-卖方成交
     *
     * Generated from protobuf field <code>uint32 tx_dir = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setTxDir($var)
    {
        GPBUtil::checkUint32($var);
        $this->tx_dir = $var;

        return $this;
    }

    /**
     *交易类型：0-成交，1-撤单
     *
     * Generated from protobuf field <code>uint32 tx_kind = 9;</code>
     * @return int
     */
    public function getTxKind()
    {
        return $this->tx_kind;
    }

    /**
     *交易类型：0-成交，1-撤单
     *
     * Generated from protobuf field <code>uint32 tx_kind = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setTxKind($var)
    {
        GPBUtil::checkUint32($var);
        $this->tx_kind = $var;

        return $this;
    }

    /**
     *买方委托序号
     *
     * Generated from protobuf field <code>string buy_order_seq = 10;</code>
     * @return string
     */
    public function getBuyOrderSeq()
    {
        return $this->buy_order_seq;
    }

    /**
     *买方委托序号
     *
     * Generated from protobuf field <code>string buy_order_seq = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setBuyOrderSeq($var)
    {
        GPBUtil::checkString($var, True);
        $this->buy_order_seq = $var;

        return $this;
    }

    /**
     *卖方委托序号
     *
     * Generated from protobuf field <code>string sell_order_seq = 11;</code>
     * @return string
     */
    public function getSellOrderSeq()
    {
        return $this->sell_order_seq;
    }

    /**
     *卖方委托序号
     *
     * Generated from protobuf field <code>string sell_order_seq = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setSellOrderSeq($var)
    {
        GPBUtil::checkString($var, True);
        $this->sell_order_seq = $var;

        return $this;
    }

}

